'use client';
import {useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import type {Society,Entry} from '@/lib/model';
import {mutate} from './fields';
const choices=[{value:'news',label:'Noticias',detail:'Textos e imágenes de las noticias.'},{value:'result',label:'Clasificaciones',detail:'Concursos, tablas, podios y archivos Excel o PDF.'},{value:'event',label:'Calendario',detail:'Concursos programados, entrenamientos y reuniones.'},{value:'photo',label:'Galería',detail:'Fotografías y pies de foto.'},{value:'member',label:'Socios',detail:'Nombres, números de socio y presentaciones.'},{value:'info',label:'Información, contacto y escudo',detail:'Presentación, historia, temporada, localidad, teléfono, correo, dirección, enlaces y escudo. Se conserva el nombre, la comunidad y la provincia.'}];
export default function DeleteContent({society,entries,onDeleted}:{society:Society;entries:Entry[];onDeleted:(removed:boolean,message:string)=>Promise<void>}){
 const [selected,setSelected]=useState<string[]>([]),[confirm,setConfirm]=useState<'content'|'society'|null>(null),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const ownEntries=entries.filter(e=>e.society_id===society.id),target=ownEntries.filter(e=>confirm==='society'||selected.includes(e.kind));
 function open(kind:'content'|'society'){setName('');setError('');setConfirm(kind);}
 async function remove(){if(!confirm||name!==society.name)return;setBusy(true);setError('');try{
 const result=await mutate({action:confirm==='society'?'delete-society':'delete-content',society_id:society.id,updated:society.updated,confirm_name:name,scopes:confirm==='society'?undefined:selected,entries:target.map(e=>({id:e.id,updated:e.updated}))});
 setConfirm(null);setSelected([]);await onDeleted(!!result.societyDeleted,result.societyDeleted?'Sociedad eliminada.':result.skipped?'Se ha eliminado el contenido seleccionado. Algunos elementos cambiaron durante la operación y se han conservado; revisa la lista.':'Contenido seleccionado eliminado.');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="delete-content"><span className="eyebrow">SOLO ADMINISTRADOR</span><h3>Eliminar contenido de {society.name}.</h3><p>Selecciona las secciones que quieres vaciar. Se incluyen los borradores y los archivos que dejen de utilizarse. Esta acción afecta únicamente a esta sociedad.</p><div className="delete-options">{choices.map(choice=><label key={choice.value} className="delete-option"><Checkbox checked={selected.includes(choice.value)} onCheckedChange={checked=>setSelected(old=>checked===true?[...old,choice.value]:old.filter(v=>v!==choice.value))}/><span><strong>{choice.label}{choice.value!=='info'?' ('+ownEntries.filter(e=>e.kind===choice.value).length+')':''}</strong><small>{choice.detail}</small></span></label>)}</div><div className="delete-toolbar"><button type="button" className="textlink" onClick={()=>setSelected(selected.length===choices.length?[]:choices.map(c=>c.value))}>{selected.length===choices.length?'Desmarcar todo':'Seleccionar todo el contenido'}</button><button type="button" className="button" disabled={!selected.length} onClick={()=>open('content')}>Eliminar lo seleccionado</button></div><p className="form-help">Para borrar solo una noticia, clasificación, foto, evento o socio, usa «Eliminar» junto a ese elemento en su sección.</p><div className="delete-society"><h3>Eliminar la sociedad completa.</h3><p>Se eliminará su página, su información, todas las publicaciones y todos los archivos. Dejará de aparecer en el directorio.</p><button type="button" className="outline-button" onClick={()=>open('society')}>Eliminar sociedad completa</button></div>
 <AlertDialog open={!!confirm} onOpenChange={open=>{if(!open&&!busy)setConfirm(null);}}><AlertDialogContent className="delete-confirm"><AlertDialogTitle>{confirm==='society'?'¿Eliminar la sociedad completa?':'¿Eliminar el contenido seleccionado?'}</AlertDialogTitle><AlertDialogDescription>Esta acción no se puede deshacer. Se eliminarán {target.length} publicaciones de «{society.name}»{confirm==='society'?', su página, información y archivos.':selected.includes('info')?' y la información, contacto y escudo seleccionados.':'.'}</AlertDialogDescription>{confirm==='content'&&<p className="deletion-summary">Secciones: {choices.filter(c=>selected.includes(c.value)).map(c=>c.label).join(', ')}.</p>}<label className="form-field">Escribe «{society.name}» para confirmar<input autoComplete="off" value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label>{error&&<p role="alert" className="error-box">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy||name!==society.name} onClick={e=>{e.preventDefault();remove();}}>{busy?'Eliminando…':'Confirmar eliminación'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>;
}
