'use client';
import {useState} from 'react';
import {type Entry,type Rank,kindLabels,eventTypes,competitionTypes,mediaUrl} from '@/lib/model';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Choice,ImageField,mutate} from './fields';
import RankingImporter from './ranking-importer';
import ClassificationTable from '@/components/classification-table';
export default function EntryForm({initial,onSaved}:{initial:Partial<Entry>;onSaved:()=>Promise<void>}){
 const [data,setData]=useState(initial),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[filename,setFilename]=useState(''),[pendingImport,setPendingImport]=useState(false);
 const kind=data.kind!,update=(key:string,value:any)=>setData(d=>({...d,[key]:value}));
 function updateRow(i:number,key:keyof Rank,value:any){update('rows',data.rows!.map((r,j)=>i===j?{...r,[key]:value}:r));}
 async function submit(e:React.FormEvent){e.preventDefault();if(uploading||pendingImport)return;setBusy(true);setError('');try{await mutate({action:'save-entry',id:initial.id,updated:initial.updated,data});await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const imported=!!data.table_data?.rows.length;
 return <form className="editor-form" onSubmit={submit}><fieldset disabled={busy||uploading}><div className="form-grid">
 <label className="form-field wide">{kind==='member'?'Nombre del socio / peña':kind==='result'?'Nombre de la competición':'Título'} *<input value={data.title} onChange={e=>update('title',e.target.value)} required minLength={2} maxLength={200}/></label>
 {kind!=='member'&&<label className="form-field">Fecha *<input type="date" value={data.date} onChange={e=>update('date',e.target.value)} required/></label>}
 {kind==='result'&&<><label className="form-field">Temporada<input value={data.season||''} onChange={e=>update('season',e.target.value)} maxLength={50} placeholder="Ej. 2026/2027"/></label><Choice id="result-category" label="Tipo de competición" value={data.category||'local'} items={competitionTypes} onChange={v=>update('category',v)}/><label className="form-field">Localidad<input value={data.location||''} onChange={e=>update('location',e.target.value)} maxLength={250} placeholder="Ej. Lorquí"/></label><p className="form-help wide">Los concursos locales aparecerán en el resumen de podios de su temporada.</p></>}
 {kind==='event'&&<><label className="form-field">Hora<input type="time" value={data.time||''} onChange={e=>update('time',e.target.value)}/></label><Choice id="event-kind" label="Tipo de evento" value={data.category||'concurso'} onChange={v=>update('category',v)} items={eventTypes}/><label className="form-field wide">Lugar<input value={data.location||''} onChange={e=>update('location',e.target.value)} maxLength={250}/></label></>}
 {(kind==='news'||kind==='member')&&<label className="form-field">{kind==='member'?'Cargo (opcional)':'Categoría (opcional)'}<input value={data.category||''} onChange={e=>update('category',e.target.value)} maxLength={80}/></label>}
 {kind==='member'&&<label className="form-field">Número de socio<input value={data.member_number||''} onChange={e=>update('member_number',e.target.value)} maxLength={40}/></label>}
 <label className="form-field wide">{kind==='news'?'Texto de la noticia *':kind==='photo'?'Pie de foto':kind==='member'?'Presentación pública (opcional)':'Información'}<textarea value={data.body} onChange={e=>update('body',e.target.value)} required={kind==='news'} rows={kind==='news'?8:3} maxLength={30000}/></label>
 {(kind==='news'||kind==='photo')&&<div className="wide"><ImageField label={kind==='photo'?'Fotografía *':'Imagen de la noticia (opcional)'} society={data.society_id!} value={data.image_key||''} onChange={v=>update('image_key',v)} onBusy={setUploading}/></div>}
 </div>
 {kind==='result'&&<div className="rank-editor"><RankingImporter society={data.society_id!} onBusy={setUploading} onPending={setPendingImport} onImported={(imported,name)=>{setData(d=>({...d,...imported}));setFilename(name);}}/>{data.file_key&&<div className="attachment-actions"><a className="textlink" href={mediaUrl(data.file_key)}>Descargar {filename||'archivo actual'}</a><button type="button" className="quiet-button" onClick={()=>{update('file_key','');setFilename('');}}>Quitar archivo adjunto</button></div>}
 {!pendingImport&&(imported?<div className="import-preview"><p><strong>{data.rows?.length?data.rows.length+' clasificados importados.':'Plantilla cargada, pendiente de resultados.'}</strong> {data.table_data!.headers.length} columnas · {data.table_data!.rows.length} filas.</p><p className="form-help">Puedes guardar la clasificación. La tabla completa conservará todas las filas y columnas del Excel.</p><ClassificationTable table={data.table_data!} limit={5} label="Vista previa de la clasificación cargada"/><button type="button" className="outline-button" onClick={()=>setData(d=>({...d,table_data:{headers:[],rows:[]},file_key:''}))}>Pasar a edición manual</button><p className="form-help">Al pasar a edición manual se conservan las posiciones, participantes, palomos y puntos, y se retira el Excel y sus columnas adicionales.</p></div>:<><p>Introduce las posiciones oficiales. Se mostrarán en ese orden.</p><Table><TableHeader><TableRow><TableHead>Pos.</TableHead><TableHead>Colombicultor / peña</TableHead><TableHead>Palomo</TableHead><TableHead>Puntos</TableHead><TableHead><span className="sr-only">Quitar</span></TableHead></TableRow></TableHeader><TableBody>{data.rows?.map((r,i)=><TableRow key={i}><TableCell><input aria-label={'Posición fila '+(i+1)} type="number" min="1" max="100000" step="1" required value={r.position} onChange={e=>updateRow(i,'position',e.target.value===''?'':Number(e.target.value))}/></TableCell><TableCell><input aria-label={'Participante fila '+(i+1)} required maxLength={180} value={r.participant} onChange={e=>updateRow(i,'participant',e.target.value)}/></TableCell><TableCell><input aria-label={'Palomo fila '+(i+1)} maxLength={180} value={r.pigeon} onChange={e=>updateRow(i,'pigeon',e.target.value)}/></TableCell><TableCell><input aria-label={'Puntos fila '+(i+1)} type="number" min="0" max="100000000" step="any" required value={r.points} onChange={e=>updateRow(i,'points',e.target.value===''?'':Number(e.target.value))}/></TableCell><TableCell><button type="button" className="quiet-button" aria-label={'Quitar fila '+(i+1)} onClick={()=>update('rows',data.rows!.filter((_,j)=>j!==i))}>×</button></TableCell></TableRow>)}</TableBody></Table><button className="outline-button" type="button" disabled={(data.rows?.length||0)>=1000} onClick={()=>update('rows',[...(data.rows||[]),{position:Math.max(0,...(data.rows||[]).map(r=>Number(r.position)))+1,participant:'',pigeon:'',points:0}])}>＋ Añadir fila</button></>)}
 </div>}
 {kind==='news'&&<div className="news-publication-options"><h3>Visibilidad e importancia</h3><label className="check-line"><Checkbox checked={data.news_featured===true} onCheckedChange={v=>update('news_featured',v===true)}/> Destacar en la página principal</label><p className="form-help">Aparecerá en «Noticias destacadas» de Inicio con su titular, imagen y resumen. Puedes desmarcar esta opción sin borrar la noticia.</p><label className="form-field news-priority-field">Prioridad (1 = más importante)<input type="number" min="1" max="999" step="1" required value={data.news_priority??100} onChange={e=>update('news_priority',e.target.value===''?'':Number(e.target.value))} aria-describedby="news-priority-help"/></label><p className="form-help" id="news-priority-help">Un número menor aparece antes, tanto en Inicio como en los listados de noticias. Si empatan, se muestra primero la más reciente. Prioridad normal: 100.</p>{data.news_featured&&!data.published&&<p className="news-publication-notice">Para que se vea en Inicio, marca también «Publicar en la página de esta sociedad». La sociedad debe estar publicada.</p>}</div>}
 <label className="check-line"><Checkbox checked={!!data.published} onCheckedChange={v=>update('published',v===true?1:0)}/> Publicar en la página de esta sociedad</label><p className="form-help">Sin marcar, solo tú podrás ver este contenido. La sociedad también debe estar publicada.</p>{pendingImport&&!uploading&&<p className="form-help">Revisa el archivo y aplica los ajustes de importación, o cancélalos para continuar.</p>}{error&&<div role="alert" className="error-box">{error}</div>}<button className="button" disabled={busy||uploading||pendingImport}>{busy?'Guardando…':'Guardar '+kindLabels[kind]}</button></fieldset></form>;
}
