'use client';
import { useEffect,useState } from 'react';
import Shell from '@/components/site-shell';
import SocietyForm from './society-form';
import EntryForm from './entry-form';
import DeleteContent from './delete-content';
import {Choice,mutate} from './fields';
const sections=[{kind:'news',label:'Noticias'},{kind:'event',label:'Calendario'},{kind:'result',label:'Clasificaciones'},{kind:'photo',label:'Galería'},{kind:'member',label:'Socios'}] as const;
import { regions,displayDate,compareNews,type Society,type Entry,type Rank,type EntryKind,kindLabels } from '@/lib/model';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { Skeleton } from '@/components/ui/skeleton';

function Blank({title,detail}:{title:string;detail:string}){return <Empty className="blank"><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{detail}</EmptyDescription></EmptyHeader></Empty>}

export default function Admin({user}:{user:string}){
 const [societies,setSocieties]=useState<Society[]>([]),[entries,setEntries]=useState<Entry[]>([]),[selected,setSelected]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[adding,setAdding]=useState(false),[entry,setEntry]=useState<Partial<Entry>|null>(null),[removing,setRemoving]=useState<Entry|null>(null),[busy,setBusy]=useState(false),[activeTab,setActiveTab]=useState('info');
 const society=societies.find(s=>s.id===selected);
 async function refresh(){try{const r=await fetch('/api/data?manage=1');const data:any=await r.json();if(!r.ok)throw new Error(data.error);setSocieties(data.societies);setEntries(data.entries);setError('');return true;}catch(e){setError((e as Error).message);return false;}finally{setLoading(false);}}
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setSelected(q.get('society')||'');const tab=q.get('tab');if(tab==='info'||tab==='delete'||sections.some(s=>s.kind===tab))setActiveTab(tab!);refresh();},[]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const life=new AbortController();Promise.resolve(mc.registerTool({name:'start_society_creation',title:'Preparar una sociedad',description:'Abre el formulario para crear una sociedad; no guarda ni publica datos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(!input||Object.keys(input).length)throw new Error('No se aceptan parámetros.');setAdding(true);return{status:'form_open'};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[]);
 function newEntry(kind:EntryKind){setEntry({society_id:selected,kind,title:'',date:new Date().toISOString().slice(0,10),body:'',published:0,category:kind==='event'?'concurso':kind==='result'?'local':'',season:society?.season||'',image_key:'',file_key:'',table_data:{headers:[],rows:[]},rows:kind==='result'?[{position:1,participant:'',pigeon:'',points:0}]:[]});}
 async function deleteEntry(){if(!removing)return;setBusy(true);try{await mutate({action:'delete-entry',id:removing.id,updated:removing.updated});setRemoving(null);await refresh();setMessage('Contenido eliminado.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const visible=filter==='all'?societies:societies.filter(s=>s.region===filter);
 return <Shell admin canManage><section className="admin-top"><div><div className="breadcrumb"><a href="/">Inicio</a> / Gestión</div><span className="eyebrow">EL ESPACIO DE TUS SOCIEDADES</span><h1>Gestionar sociedades.</h1><p>Crea una sociedad y actualiza su contenido desde aquí.</p></div><div className="admin-top-actions"><button className="button" onClick={()=>{setMessage('');setAdding(true);}}>＋ Nueva sociedad</button><a className="textlink" href="/sociedad/plantilla">Ver plantilla ↗</a></div></section>
 <div className="admin-content"><div className="account-line"><span>{societies.length} {societies.length===1?'sociedad':'sociedades'} · {societies.filter(s=>s.published).length} publicadas</span><span>Sesión: {user}</span></div>
 {error&&<div className="error-box" role="alert">{error} <button className="textlink" onClick={refresh}>Reintentar</button></div>}{message&&<p className="success-box" role="status">{message}</p>}
 <div className="admin-columns"><aside className="society-sidebar"><Choice id="region-filter" label="Comunidad" value={filter} onChange={setFilter} items={[{value:'all',label:'Todas las comunidades'},...regions.map(r=>({value:r.id,label:r.name}))]}/>
 {loading?<Skeleton className="h-32 mt-5"/>:<div className="society-selector">{visible.map(s=><button key={s.id} aria-pressed={s.id===selected} className={s.id===selected?'chosen':''} onClick={()=>{setSelected(s.id);setMessage('');setActiveTab('info');}}><span>{s.name}</span><small>{s.town||s.province} · {s.published?'Publicada':'Borrador'}</small></button>)}{!visible.length&&<p>No hay sociedades en esta comunidad.</p>}</div>}</aside>
 <section className="editor-area">{!society?<><Blank title={societies.length?'Selecciona una sociedad':'Tu primera sociedad empieza aquí.'} detail={societies.length?'Elige una sociedad del listado para editar su información, noticias y clasificaciones.':'Solo necesitas su nombre y ubicación. La página se crea con el diseño de ClasiColombicultura.'}/><div className="empty-action"><button className="button" onClick={()=>setAdding(true)}>＋ Nueva sociedad</button></div></>:<>
 <div className="editor-title"><div><span className="eyebrow">{regions.find(r=>r.id===society.region)?.name} · {society.province}</span><h2>{society.name}</h2></div><a className="textlink" href={'/sociedad/'+society.slug}>{society.published?'Ver página':'Vista previa'} ↗</a></div>
 <Tabs value={activeTab} onValueChange={setActiveTab} className="site-tabs"><TabsList><TabsTrigger value="info">Información</TabsTrigger>{sections.map(section=><TabsTrigger key={section.kind} value={section.kind}>{section.label} ({entries.filter(e=>e.society_id===selected&&e.kind===section.kind).length})</TabsTrigger>)}<TabsTrigger value="delete">Eliminar contenido</TabsTrigger></TabsList>
 <TabsContent value="info"><SocietyForm key={society.id+'-'+society.updated} initial={society} onSaved={async()=>{await refresh();setMessage('Información de la sociedad guardada.');}}/></TabsContent>
 {sections.map(({kind,label})=><TabsContent value={kind} key={kind}><div className="content-toolbar"><h3>{label+' de la sociedad'}</h3><button className="button" onClick={()=>newEntry(kind)}>＋ {'Añadir '+kindLabels[kind]}</button></div>{!entries.some(e=>e.society_id===selected&&e.kind===kind)?<Blank title={'Todavía no has añadido contenido en '+label.toLowerCase()+'.'} detail="El contenido que añadas aquí pertenecerá únicamente a esta sociedad."/>:entries.filter(e=>e.society_id===selected&&e.kind===kind).sort(kind==='news'?compareNews:()=>0).map(e=><article className="entry-row" key={e.id}><div><span className="entry-meta">{displayDate(e.date)} · {e.published?'Publicado':'Borrador'}</span><h3>{e.title}</h3>{kind==='news'&&<p className="entry-news-status">Prioridad {e.news_priority??100}{e.news_featured?(e.published&&society.published?' · Destacada en Inicio':' · Seleccionada para Inicio (pendiente de publicación)'):' · Sin destacar en Inicio'}</p>}{kind==='result'&&<p>{e.rows.length} participantes</p>}</div><div className="row-actions"><button className="textlink" onClick={()=>setEntry(e)}>Editar</button><button className="quiet-button" onClick={()=>setRemoving(e)}>Eliminar</button></div></article>)}</TabsContent>)}
 <TabsContent value="delete"><DeleteContent key={society.id+'-'+society.updated} society={society} entries={entries} onDeleted={async(removed,message)=>{await refresh();if(removed){setSelected('');setActiveTab('info');}setMessage(message);}}/></TabsContent>
 </Tabs></>}</section></div></div>
 <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="edit-dialog"><DialogTitle>Nueva sociedad</DialogTitle><DialogDescription>El mismo diseño, con su propio nombre y contenido. Se creará como borrador.</DialogDescription><SocietyForm compact onSaved={async(data)=>{window.location.assign('/sociedad/'+encodeURIComponent(data.slug));}}/></DialogContent></Dialog>
 <Dialog open={!!entry} onOpenChange={open=>{if(!open)setEntry(null);}}><DialogContent className="edit-dialog wide-dialog"><DialogTitle>{entry?.id?'Editar':'Añadir'} {entry?.kind?kindLabels[entry.kind]:''}</DialogTitle><DialogDescription>{society?.name}</DialogDescription>{entry&&<EntryForm initial={entry} onSaved={async()=>{setEntry(null);await refresh();setMessage('Contenido guardado.');}}/>}</DialogContent></Dialog>
 <AlertDialog open={!!removing} onOpenChange={o=>{if(!o&&!busy)setRemoving(null);}}><AlertDialogContent><AlertDialogTitle>¿Eliminar este contenido?</AlertDialogTitle><AlertDialogDescription>Se eliminará «{removing?.title}» de esta sociedad. No se puede deshacer.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();deleteEntry();}}>{busy?'Eliminando…':'Eliminar'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </Shell>;
}
