'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import Shell from '@/components/site-shell';
import BackLink from '@/components/back-link';
import PublicImage from '@/components/public-image';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ClassificationTable,{manualClassification} from '@/components/classification-table';
import {Calendar} from '@/components/ui/calendar';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {es} from 'date-fns/locale';
import {entrySeason,podiumContests,podiumRows} from '@/lib/season-summary';
import {regions,displayDate,eventTypes,competitionLabel,compareNews,type Society,type Entry,type Rank} from '@/lib/model';
const tabs=[['inicio','Inicio','info'],['sociedad','Sociedad','info'],['noticias','Noticias','news'],['calendario','Calendario','event'],['clasificaciones','Clasificaciones','result'],['galeria','Galería','photo'],['contacto','Contacto','info']] as const;
function Meta({entry:e}:{entry:Entry}){return <span className="eyebrow">{displayDate(e.date)}{e.kind==='result'?' · '+competitionLabel(e.category):e.category?' · '+e.category:''}{!e.published?' · BORRADOR':''}</span>}
function EmptySection({children}:{children:React.ReactNode}){return <div className="society-empty"><p>{children}</p></div>}
function News({entry:e,published}:{entry:Entry;published:boolean}){return <article className="society-news" id={e.id}>{e.image_key&&<PublicImage className="news-photo" imageKey={e.image_key} published={published&&e.published===1} alt=""/>}<Meta entry={e}/><h2>{e.title}</h2><p className="preserve-lines">{e.body}</p></article>}
function RankTable({rows}:{rows:Rank[]}){return <Table><TableHeader><TableRow><TableHead>Posición</TableHead><TableHead>Colombicultor / peña</TableHead><TableHead>Palomo</TableHead><TableHead>Puntos</TableHead></TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}><TableCell className="rank-number">{r.position}</TableCell><TableCell>{r.participant}</TableCell><TableCell>{r.pigeon||'—'}</TableCell><TableCell className="points">{r.points.toLocaleString('es-ES',{maximumFractionDigits:8})}</TableCell></TableRow>)}</TableBody></Table>}
export function Rankings({entries,defaultSeason,slug}:{entries:Entry[];defaultSeason:string;slug:string}){
 const seasons=[...new Set(entries.map(e=>entrySeason(e,defaultSeason)))].sort().reverse(),[season,setSeason]=useState('all'),[competition,setCompetition]=useState('');
 const matches=entries.filter(e=>season==='all'||entrySeason(e,defaultSeason)===season);
 const selected=matches.some(e=>e.id===competition)?competition:matches[0]?.id||'';
 // The podium archive uses all competitions in the season, never just the active tab.
 const summary=podiumContests(entries,defaultSeason,season),contestCount=summary.length;
 function openContest(id:string){setCompetition(id);requestAnimationFrame(()=>{const contest=document.getElementById('contest-'+id);contest?.focus({preventScroll:true});contest?.scrollIntoView({behavior:'smooth',block:'start'});});}
 return <><div className="ranking-filters competition-season-filter"><div><label htmlFor="season-filter">Temporada</label><Select value={season} onValueChange={v=>{setSeason(v);setCompetition('');}}><SelectTrigger id="season-filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas las temporadas</SelectItem>{seasons.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div></div>

 {!entries.length&&<EmptySection>Las clasificaciones se publicarán aquí cuando estén disponibles.</EmptySection>}
 {!!entries.length&&!matches.length&&<EmptySection>No hay clasificaciones en esta temporada.</EmptySection>}
 {!!matches.length&&<Tabs className="competition-tabs" value={selected} onValueChange={setCompetition}>
 <TabsList className="competition-tab-list" aria-label="Seleccionar concurso">{matches.map(e=><TabsTrigger className="competition-tab" key={e.id} value={e.id} title={displayDate(e.date)+' · '+entrySeason(e,defaultSeason)}>{e.title}</TabsTrigger>)}</TabsList>
 {matches.map(e=>{const rows=[...e.rows].sort((a,b)=>a.position-b.position);return <TabsContent className="competition-panel" value={e.id} key={e.id}><article className="ranking" id={'contest-'+e.id} tabIndex={-1}><div className="ranking-heading"><Meta entry={e}/><h2>{e.title}</h2>{e.location&&<p className="competition-location"><strong>Localidad:</strong> {e.location}</p>}{e.season&&<p className="season-label">Temporada {e.season}</p>}{e.body&&<p className="preserve-lines">{e.body}</p>}</div>
 <div className="ranking-heading"><h3>Primeros 10 clasificados</h3>{!rows.length&&<p>Plantilla pendiente de resultados.</p>}</div>
 {(e.table_data?.headers.length>0||rows.length>0)&&<ClassificationTable table={e.table_data?.headers.length?e.table_data:manualClassification(rows)} limit={10} label={'Primeros 10 clasificados de '+e.title}/>}
 <div className="classification-link"><a className="button" href={'/sociedad/'+encodeURIComponent(slug)+'/clasificacion/'+encodeURIComponent(e.id)}>Ver clasificación completa ↗</a><span>{e.table_data?.headers.length?e.table_data.rows.length+' filas · '+e.table_data.headers.length+' columnas':rows.length+' clasificados'}</span></div></article></TabsContent>;})}</Tabs>}
 <section className="season-summary" aria-labelledby="season-summary-title"><div className="section-heading"><div><span className="eyebrow">RESUMEN DE TEMPORADA</span><h2 id="season-summary-title">Podios de los concursos.</h2></div><span>{contestCount} {contestCount===1?'concurso':'concursos'}</span></div>
 {summary.length?<div className="season-podium-grid" data-compact={contestCount>7||undefined} style={{'--podium-columns':Math.min(9,contestCount)} as CSSProperties}>{summary.map(e=><article className="season-podium-card" key={e.id}><div className="season-podium-heading"><Meta entry={e}/><h3>{e.title}</h3><p className="podium-season">Temporada {entrySeason(e,defaultSeason)}</p>{e.location&&<p className="podium-location">{e.location}</p>}</div><ol className="season-winners">{podiumRows(e.rows).map(({position,winners})=><li className={'season-place season-place-'+position} key={position}><span className="season-medal" aria-label={'Puesto '+position}>{position}º</span><div>{winners.length?winners.map((r,i)=><div className="season-winner" key={i}><strong>{r.pigeon||r.participant}</strong>{r.pigeon&&r.participant!=='—'&&<span>{r.participant}</span>}<small>{r.points.toLocaleString('es-ES',{maximumFractionDigits:8})} puntos</small></div>):<span className="pending-winner">Pendiente de resultado</span>}</div></li>)}</ol><button type="button" className="textlink" onClick={()=>openContest(e.id)}>Ver clasificación ↗</button></article>)}</div>:<EmptySection>No hay concursos en esta temporada. Los podios aparecerán al publicar sus clasificaciones.</EmptySection>}
 </section></>;
}
const dayKey=(date:Date)=>date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');
function Agenda({events}:{events:Entry[]}){
 const [month,setMonth]=useState(new Date()),[day,setDay]=useState<Date>();
 const today=dayKey(new Date()),upcoming=events.filter(e=>e.date>=today).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 return <div className="calendar-layout"><div className="calendar-box"><Calendar locale={es} weekStartsOn={1} mode="single" selected={day} onSelect={setDay} month={month} onMonthChange={m=>{setMonth(m);setDay(undefined);}} modifiers={{event:events.map(e=>new Date(e.date+'T12:00:00'))}} modifiersClassNames={{event:'has-society-event'}}/><div className="calendar-actions"><button className="textlink" onClick={()=>{setMonth(new Date());setDay(new Date());}}>Hoy</button></div><p className="form-help">Los días marcados tienen actividad.</p></div><div><h3>Próximos eventos</h3>{!upcoming.length?<EmptySection>No hay próximos eventos publicados.</EmptySection>:upcoming.map(e=><article className="event-card" key={e.id}><span className="eyebrow">{displayDate(e.date)}{e.time?' · '+e.time:''}{!e.published?' · BORRADOR':''}</span><span className="event-type">{eventTypes.find(t=>t.value===e.category)?.label||e.category}</span><h3>{e.title}</h3>{e.location&&<p><strong>Lugar:</strong> {e.location}</p>}{e.body&&<p className="preserve-lines">{e.body}</p>}</article>)}</div></div>;
}
export default function SocietyPage({society:s,entries,owner=false,demo=false}:{society:Society;entries:Entry[];owner?:boolean;demo?:boolean}){
 const region=regions.find(r=>r.id===s.region)!,[tab,setTab]=useState('inicio'),[photo,setPhoto]=useState<Entry|null>(null);
 const news=entries.filter(e=>e.kind==='news').sort(compareNews),results=entries.filter(e=>e.kind==='result'),events=entries.filter(e=>e.kind==='event'),photos=entries.filter(e=>e.kind==='photo'),members=entries.filter(e=>e.kind==='member').sort((a,b)=>(a.member_number||a.title).localeCompare(b.member_number||b.title,'es',{numeric:true}));
 useEffect(()=>{const read=()=>{const key=window.location.hash.slice(1);setTab(tabs.some(t=>t[0]===key)?key:'inicio');};read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read);},[]);
 function navigate(v:string,event?:React.MouseEvent<HTMLAnchorElement>){if(event&&(event.metaKey||event.ctrlKey||event.shiftKey||event.altKey||event.button!==0))return;event?.preventDefault();setTab(v);window.history.replaceState(window.history.state,'','#'+v);}
 const edit=(section='info')=>'/admin?society='+encodeURIComponent(s.id)+'&tab='+section;
 const next=events.filter(e=>e.date>=dayKey(new Date())).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0];
 return <Shell canManage={owner}>{demo?<div className="preview-notice"><strong>Vista de plantilla.</strong> Cada sociedad tendrá su nombre, escudo y contenido.{owner&&<a href="/admin">Crear una sociedad ↗</a>}</div>:owner&&<div className="preview-notice owner-toolbar"><span>{s.published?'Vista de administrador · Sociedad publicada':'Vista previa · Esta sociedad es un borrador, solo tú puedes verla'}</span><a href={edit(tabs.find(t=>t[0]===tab)?.[2])}>Editar esta sociedad ↗</a></div>}
 <section className="society-hero"><div><BackLink href={'/#comunidades/'+s.region+'/'+s.province.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replaceAll(' ','-')}/><div className="breadcrumb"><a href="/#comunidades">Comunidades</a> / <a href={'/#comunidades/'+s.region}>{region.name}</a> / {s.province}</div><div className="society-identity">{s.crest_key&&<PublicImage className="society-crest" imageKey={s.crest_key} published={s.published===1} variant="crest" alt={'Escudo de '+s.name} loading="eager"/>}<div><span className="eyebrow">SOCIEDAD DE COLOMBICULTURA{s.season?' · TEMPORADA '+s.season:''}</span><h1>{s.name}</h1><p><img src={'/symbols/flag-'+s.region+'.svg'} alt="" width="32" height="22"/>{s.town||s.province} · {region.name}</p></div></div></div><div className="society-photo"><img src="/palomos.webp" alt="Palomos de colores en vuelo"/></div></section>
 <section className="society-body"><Tabs value={tab} onValueChange={navigate} className="site-tabs society-tabs"><TabsList aria-label="Contenido de la sociedad">{tabs.map(([key,label])=><TabsTrigger key={key} value={key}>{label}</TabsTrigger>)}</TabsList>
 <TabsContent value="inicio"><div className="society-welcome"><span className="eyebrow">BIENVENIDOS A NUESTRA SOCIEDAD</span><h2>{s.headline||'Nuestra afición, nuestra sociedad.'}</h2><p className="preserve-lines">{s.intro||'El punto de encuentro para seguir la actualidad, las actividades y las competiciones de '+s.name+'.'}</p><a className="textlink" href="#sociedad" onClick={event=>navigate('sociedad',event)}>Conoce nuestra sociedad ↗</a></div><div className="society-home-grid"><section className="home-section"><div className="section-heading"><h2>Últimas noticias.</h2><a className="textlink" href="#noticias" onClick={event=>navigate('noticias',event)}>Ver todas ↗</a></div>{news.length?news.slice(0,2).map(e=><article className="news-summary" key={e.id}>{e.image_key&&<PublicImage imageKey={e.image_key} published={s.published===1&&e.published===1} variant="summary" alt=""/>}<div><Meta entry={e}/><h3><a href="#noticias" onClick={event=>navigate('noticias',event)}>{e.title}</a></h3><p>{e.body.slice(0,200)}{e.body.length>200?'…':''}</p></div></article>):<EmptySection>Todavía no hay noticias publicadas.</EmptySection>}</section><aside><section className="home-section compact-feature"><span className="eyebrow">LA PRÓXIMA CITA</span><h2>{next?.title||'Nuestro calendario.'}</h2><p>{next?displayDate(next.date)+(next.time?' · '+next.time:''):'Aquí encontrarás los próximos concursos, entrenamientos y reuniones.'}</p>{next?.location&&<p>{next.location}</p>}<a className="textlink" href="#calendario" onClick={event=>navigate('calendario',event)}>Ver calendario ↗</a></section><section className="home-section compact-feature"><span className="eyebrow">EN COMPETICIÓN</span><h2>{results[0]?.title||'Nuestras clasificaciones.'}</h2><p>{results.length?'Consulta los resultados y las posiciones de nuestras competiciones.':'Publicaremos aquí los resultados de nuestras competiciones.'}</p><a className="textlink" href="#clasificaciones" onClick={event=>navigate('clasificaciones',event)}>Ver clasificaciones ↗</a></section></aside></div></TabsContent>
 <TabsContent value="sociedad"><div className="information-grid"><article><span className="eyebrow">NUESTRA SOCIEDAD</span><h2>Un lugar para nuestra afición.</h2><p className="preserve-lines">{s.description||'Próximamente podrás conocer más sobre nuestra historia y actividad.'}</p></article><aside><h3>{s.name}</h3>{s.crest_key&&<PublicImage className="about-crest" imageKey={s.crest_key} published={s.published===1} variant="crest" alt={'Escudo de '+s.name}/>}<p>{s.town||s.province} · {region.name}</p>{s.season&&<p>Temporada {s.season}</p>}</aside></div><section className="members-section"><div className="section-heading"><h2>Nuestros socios.</h2>{owner&&!demo&&<a className="textlink" href={edit('member')}>Editar socios ↗</a>}</div>{members.length?<Table><TableHeader><TableRow><TableHead>Nº socio</TableHead><TableHead>Socio / peña</TableHead><TableHead>Cargo</TableHead></TableRow></TableHeader><TableBody>{members.map(e=><TableRow key={e.id}><TableCell>{e.member_number||'—'}</TableCell><TableCell><strong>{e.title}</strong>{!e.published&&<small> · Borrador</small>}{e.body&&<p className="preserve-lines">{e.body}</p>}</TableCell><TableCell>{e.category||'—'}</TableCell></TableRow>)}</TableBody></Table>:<EmptySection>La información de nuestros socios aparecerá aquí.</EmptySection>}</section></TabsContent>
 <TabsContent value="noticias"><div className="section-heading"><h2>La actualidad de nuestra sociedad.</h2></div>{news.length?news.map(e=><News key={e.id} entry={e} published={s.published===1}/>):<EmptySection>Todavía no hay noticias publicadas.</EmptySection>}</TabsContent>
 <TabsContent value="calendario"><div className="section-heading"><h2>Nuestro calendario.</h2></div><Agenda events={events}/></TabsContent>
 <TabsContent value="clasificaciones"><div className="section-heading"><h2>Clasificaciones de nuestras competiciones.</h2></div><Rankings entries={results} defaultSeason={s.season} slug={s.slug}/></TabsContent>
 <TabsContent value="galeria"><div className="section-heading"><h2>La afición, en imágenes.</h2></div>{photos.length?<div className="gallery-grid">{photos.map(e=><button className="gallery-item" onClick={()=>setPhoto(e)} key={e.id}><PublicImage imageKey={e.image_key} published={s.published===1&&e.published===1} variant="gallery" alt={e.title}/><span><strong>{e.title}</strong>{!e.published&&<small> · Borrador</small>}</span></button>)}</div>:<EmptySection>Próximamente compartiremos fotografías de nuestra sociedad.</EmptySection>}</TabsContent>
 <TabsContent value="contacto"><div className="information-grid"><article><span className="eyebrow">HABLEMOS DE NUESTRA AFICIÓN</span><h2>Contacta con {s.name}.</h2><p>Encuéntranos en {s.town||s.province}. Aquí puedes consultar los datos de contacto de nuestra sociedad.</p></article><aside><h3>Información de contacto</h3><dl><dt>Localidad</dt><dd>{s.town||s.province} · {s.province}</dd>{s.address&&<><dt>Dirección</dt><dd>{s.address}</dd></>}{s.phone&&<><dt>Teléfono</dt><dd><a href={'tel:'+s.phone.replace(/[^\d+]/g,'')}>{s.phone}</a></dd></>}{s.email&&<><dt>Correo electrónico</dt><dd><a href={'mailto:'+s.email}>{s.email}</a></dd></>}{s.social_url&&<><dt>Redes sociales</dt><dd><a className="textlink" href={s.social_url} target="_blank" rel="noopener noreferrer">Visitar perfil ↗</a></dd></>}</dl>{!s.email&&!s.phone&&!s.address&&!s.social_url&&<p>Próximamente añadiremos más datos de contacto.</p>}</aside></div></TabsContent>
 </Tabs></section><Dialog open={!!photo} onOpenChange={open=>{if(!open)setPhoto(null);}}><DialogContent className="gallery-dialog"><DialogTitle>{photo?.title}</DialogTitle><DialogDescription>{photo?displayDate(photo.date):''}</DialogDescription>{photo&&<><PublicImage imageKey={photo.image_key} published={s.published===1&&photo.published===1} alt={photo.title} loading="eager"/>{photo.body&&<p className="preserve-lines">{photo.body}</p>}</>}</DialogContent></Dialog></Shell>;
}
